#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

CONF_FILE="/etc/config/daed"

start_service() {
	[ "$(uci -q get daed.config.enabled)" = "1" ] || return 0

	local listen_addr log_maxbackups log_maxsize
	listen_addr=$(uci -q get daed.config.listen_addr || echo "0.0.0.0:2023")
	log_maxbackups=$(uci -q get daed.config.log_maxbackups || echo "1")
	log_maxsize=$(uci -q get daed.config.log_maxsize || echo "5")

	procd_open_instance "main"
	procd_set_param command /usr/bin/daed run
	procd_append_param command --listen "$listen_addr"
	
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "daed"
}
