include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DAED
LUCI_DEPENDS:=+daed
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-daed
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
